In [1]:
import pandas as pd
from pathlib import Path
import os

In [54]:
results = pd.DataFrame(columns=[
    'Slice',
    'Count C1',
    'Count C2',
    'Total Area C1',
    'Total Area C2',
    'Avg Particle Size',
    'Area of C1 / Area of C2',
    'Area of Particles (C1) / Cell',
    'Number of Particles (C1) / Cell'
])

In [32]:
def analyze_slice(pathname, slice):
    df = pd.read_csv(pathname)
    df = df.set_index('Slice')

    c1 = df.loc[f'DUP_C1-{slice}.czi']
    c2 = df.loc[f'DUP_C2-{slice}.czi']

    data = {
        'Slice': slice,
        'Count C1': c1['Count'],
        'Count C2': c2['Count'],
        'Total Area C1': c1['Total Area'],
        'Total Area C2': c2['Total Area'],
        'Avg Particle Size': c1['Average Size'],
        'Area of C1 / Area of C2': (c1['Total Area'] / c2['Total Area']).round(4),
        'Area of Particles (C1) / Cell': (c1['Total Area'] / c2['Count']).round(4),
        'Number of Particles (C1) / Cell': (c1['Count'] / c2['Count']).round(4)
    }
    results.loc[len(results)] = data
    #results = results.round(4)

    #results = pd.DataFrame(data)
    #return results
    #print(df_2.head())

In [55]:
base_pathname = '/Users/lucialiu/Downloads/2025.11.12 chow-DDC diet 6wks p62/czi/40X/Chow Final Outputs'
base_dir = Path(base_pathname)
summaries = {}
for path in base_dir.iterdir():
    #print(path)
    if path.is_dir():
        for filename in os.listdir(base_pathname + '/' + path.name):
            if 'summary' in filename:
                #print(filename)
                summaries[filename.replace('_summary.csv', '')] = (base_pathname + '/' + path.name + '/' + filename)

summaries = dict(sorted(summaries.items()))

for slice, pathname in summaries.items():
    analyze_slice(pathname, slice)

results

,Slice,Count C1,Count C2,Total Area C1,Total Area C2,Avg Particle Size,Area of C1 / Area of C2,Area of Particles (C1) / Cell,Number of Particles (C1) / Cell
0,Chow 40x 1,593.0,70.0,230.299,2808.426,0.388,0.0820,3.2900,8.4714
1,Chow 40x 2,451.0,72.0,256.515,2975.397,0.569,0.0862,3.5627,6.2639
2,Chow 40x 3,120.0,50.0,129.807,2257.719,1.082,0.0575,2.5961,2.4000
3,Chow 40x 4,945.0,69.0,434.433,2625.051,0.460,0.1655,6.2961,13.6957
4,Chow 40x 5,1213.0,82.0,419.266,2790.539,0.346,0.1502,5.1130,14.7927
5,Chow 40x 6,591.0,54.0,179.763,2828.293,0.304,0.0636,3.3289,10.9444
6,Chow 40x 7,410.0,88.0,116.139,3198.024,0.283,0.0363,1.3198,4.6591

In [56]:
base_pathname = '/Users/lucialiu/Downloads/2025.11.12 chow-DDC diet 6wks p62/czi/40X/DDC Final Outputs'
base_dir = Path(base_pathname)
summaries = {}
for path in base_dir.iterdir():
    #print(path)
    if path.is_dir():
        for filename in os.listdir(base_pathname + '/' + path.name):
            if 'summary' in filename:
                #print(filename)
                summaries[filename.replace('_summary.csv', '')] = (base_pathname + '/' + path.name + '/' + filename)

summaries = dict(sorted(summaries.items()))

for slice, pathname in summaries.items():
    analyze_slice(pathname, slice)

results = pd.concat([results.drop(index=8), results.loc[[8]]], ignore_index=True) # move DDC 40x 10 to end instead of after DDC 40x 1

results

,Slice,Count C1,Count C2,Total Area C1,Total Area C2,Avg Particle Size,Area of C1 / Area of C2,Area of Particles (C1) / Cell,Number of Particles (C1) / Cell
0,Chow 40x 1,593.0,70.0,230.299,2808.426,0.388,0.0820,3.2900,8.4714
1,Chow 40x 2,451.0,72.0,256.515,2975.397,0.569,0.0862,3.5627,6.2639
2,Chow 40x 3,120.0,50.0,129.807,2257.719,1.082,0.0575,2.5961,2.4000
3,Chow 40x 4,945.0,69.0,434.433,2625.051,0.460,0.1655,6.2961,13.6957
4,Chow 40x 5,1213.0,82.0,419.266,2790.539,0.346,0.1502,5.1130,14.7927
5,Chow 40x 6,591.0,54.0,179.763,2828.293,0.304,0.0636,3.3289,10.9444
6,Chow 40x 7,410.0,88.0,116.139,3198.024,0.283,0.0363,1.3198,4.6591
7,DDC 40x 1,643.0,128.0,939.930,6743.809,1.462,0.1394,7.3432,5.0234
8,DDC 40x 2,750.0,90.0,896.264,3850.411,1.195,0.2328,9.9585,8.3333
9,DDC 40x 3a,550.0,132.0,1624.425,5538.402,2.954,0.2933,12.3062,4.1667
10,DDC 40x 3b,838.0,142.0,863.351,5257.286,1.030,0.1642,6.0799,5.9014
11,DDC 40x 4,826.0,107.0,1122.173,6822.238,1.359,0.1645,10.4876,7.7196
12,DDC 40x 5,1400.0,77.0,1092.884,2538.252,0.781,0.4306,14.1933,18.1818
13,DDC 40x 6,820.0,98.0,1429.772,4779.070,1.744,0.2992,14.5895,8.3673
14,DDC 40x 7,868.0,88.0,1348.017,4192.858,1.553,0.3215,15.3184,9.8636
15,DDC 40x 8,743.0,102.0,1193.788,7875.162,1.607,0.1516,11.7038,7.2843
16,DDC 40x 9,398.0,62.0,532.492,1825.854,1.338,0.2916,8.5886,6.4194
17,DDC 40x 10,524.0,80.0,686.274,3602.452,1.310,0.1905,8.5784,6.5500

In [57]:
results.to_csv('/Users/lucialiu/Downloads/2025.11.12 chow-DDC diet 6wks p62/czi/40X/chow_DDC_summary.csv')